services:
  - type: web
    name: migrada-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn -w 2 -k sync -b 0.0.0.0:$PORT backend.app:app
    autoDeploy: true
    healthCheckPath: /api/carreras
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_ENV
        value: production
